[package]
name = "hello-rocket"
version = "0.1.0"
authors = ["ervinismu <social.ervin@gmail.com>"]

[dependencies]
rocket = "0.3.15"
rocket_codegen = "0.3.15"

[dependencies.rocket_contrib]
version = "0.3.15"
features = ["handlebars_templates"]